# -*- coding: utf-8 -*-
"""genetic_algo.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1P0A4wpc1uNz5wP20L8SovXhnHCbxX_aJ
"""

import random

# ==========================
# Genetic Algorithm Settings
# ==========================
POP_SIZE = 20
CHROMOSOME_LENGTH = 8
GENERATIONS = 5
MUTATION_RATE = 0.2
CROSSOVER_RATE = 0.3

# ==========================
# Helper Functions
# ==========================

def create_individual():
    """Create a random binary chromosome."""
    return [random.randint(0, 1) for _ in range(CHROMOSOME_LENGTH)]


def decode(chromosome):
    """Convert binary chromosome to integer."""
    return int("".join(map(str, chromosome)), 2)


def fitness(chromosome):
    """Fitness function: f(x) = x²"""
    x = decode(chromosome)
    return x ** 2


def create_population():
    return [create_individual() for _ in range(POP_SIZE)]


# ==========================
# Selection (Tournament)
# ==========================

def tournament_selection(population):
    tournament = random.sample(population, 3)
    tournament.sort(key=fitness, reverse=True)
    return tournament[0][:]


# ==========================
# Crossover
# ==========================

def crossover(parent1, parent2):
    if random.random() < CROSSOVER_RATE:
        point = random.randint(1, CHROMOSOME_LENGTH - 1)
        child1 = parent1[:point] + parent2[point:]
        child2 = parent2[:point] + parent1[point:]
        return child1, child2
    return parent1[:], parent2[:]


# ==========================
# Mutation
# ==========================

def mutate(chromosome):
    for i in range(CHROMOSOME_LENGTH):
        if random.random() < MUTATION_RATE:
            chromosome[i] = 1 - chromosome[i]
    return chromosome


# ==========================
# Main Genetic Algorithm
# ==========================

def genetic_algorithm():
    population = create_population()

    for generation in range(GENERATIONS):

        # Create new population
        new_population = []

        while len(new_population) < POP_SIZE:
            parent1 = tournament_selection(population)
            parent2 = tournament_selection(population)

            child1, child2 = crossover(parent1, parent2)

            child1 = mutate(child1)
            child2 = mutate(child2)

            new_population.extend([child1, child2])

        population = new_population[:POP_SIZE]

        # Best individual
        best = max(population, key=fitness)
        print(
            f"Generation {generation+1:2d} | "
            f"Best x = {decode(best):3d} | "
            f"Fitness = {fitness(best)}"
        )

    best = max(population, key=fitness)

    print("\nFinal Solution")
    print("----------------")
    print("Chromosome:", "".join(map(str, best)))
    print("x =", decode(best))
    print("Fitness =", fitness(best))


# ==========================
# Run
# ==========================

if __name__ == "__main__":
    genetic_algorithm()

